spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/booksy-clone
    username: postgres
    password: postgres
  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true