name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_NAME: booksy-clone
  JAVA_VERSION: 21
  DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle & Execute 'build' task
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          arguments: build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.DISTRIBUTION}}

      - name: Setup Gradle & Execute 'test' task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test
